Add ekg-capture/edit-abort function
ahyatt/ekg pull request #122
Opened 2023-12-07 00:30 UTC by qingshuizheng

Why this commit:

I personally want to have an abort function, so that I could decide where the note should go. Even the note has been auto-saved as draft by `ekg-auto-save-mode` (my personal branch), with `ekg-capture-abort`, the note still could go to trash. Or when I edit a note but later I decide not to save it at all, `ekg-edit-abort` could abort all the edits.

Changes in this commit:

1. In `ekg-edit-mode`: abort edit -> restore note to its original state. (Except for modification time: `ekg-save-note` recalculates it finally. Q: Any function to compare the new note vs the note in db: if value are the same, don't update the modification time?)

2. In `ekg-capture-mode`: abort capture -> trashing the note.

3. Clean up some whitespaces and bad indentations around the edits.

This commit also address https://github.com/ahyatt/ekg/pull/19 :

> Do we want C-c C-k to abort the capture process?

2023-12-07 23:46 UTC, qingshuizheng commented
> An aborted note doesn't seem to rise to that level.

I think you are right, I would change the code to adapt to this idea.

Also, I add a new local variable `ekg-kill-buffer-query-function`, which adaptive from builtin `kill-buffer-query-function`, to deal with modified buffer. Whether or not save the buffer on buffer kill, should be decided by the user.

2023-12-08 00:41 UTC, qingshuizheng commented
I'll need to make some adjustment to `kill-buffer-query-function` to adapt it to `ekg-capture-abort`, convert this pr to drafts for the moment.

2023-12-09 04:08 UTC, ahyatt requested changes

2023-12-09 04:08 UTC, ahyatt commented on ekg.el
> +(defun ekg-set-local-variables ()
This is a private function, so should be `ekg--set-local-variables`

2023-12-09 04:08 UTC, ahyatt commented on ekg.el
> +    (when (or arg (y-or-n-p "Are you sure to delete this note?"))
I think the text you changed was clearer, the new text doesn't seem correct.

2023-12-09 04:08 UTC, ahyatt commented on ekg.el
> +(defun ekg-kill-buffer-query-function ()
There should probably be a customization variable  here.  Not everyone may want to have this confirmation.  For me, for example, I often want to kill unsaved notes, so would prefer not to have confirmation.

2023-12-09 06:05 UTC, qingshuizheng commented on ekg.el
> +    (when (or arg (y-or-n-p "Are you sure to delete this note?"))
I thought the two were equivalent :-(

2023-12-09 06:07 UTC, qingshuizheng commented on ekg.el
> +(defun ekg-kill-buffer-query-function ()
Let me think about that and come up with an update.

2023-12-11 20:44 UTC, qingshuizheng commented on ekg.el
> +(defun ekg-kill-buffer-query-function ()
Just pushed a few commits:
1. reword the y-or-n-p prompt
2. internalize ekg-set-local-variables -> ekg--set-local-variables
3. add user option: ekg-save-action-on-buffer-kill

Options are:
a. abort-unsaved: only aborted the unsaved changes
b. abort-all: discard the whole capture in capture-mode; discard all edits in edit mode
c. save: save note
d. query: ask before kill

These options are somewhat opinionated, let me know what you think. :-)

2023-12-12 01:26 UTC, ahyatt requested changes

2023-12-12 03:56 UTC, qingshuizheng commented on ekg.el
> +                 (const :tag "Abort unsaved changes" abort-unsaved)
Yes, it's quite hard to precisely describe what's the main difference :-(

1. abort-unsaved: 
In ekg-capture-mode, unsaved changes will be discarded. The already saved part (by manually, or automatically save) will be kept.

2. abort-all:
For ekg-capture-mode: the whole capture will be aborted.
For ekg-edit-mode: all edits (saved or not) will be discarded; the note will be restored to the state when it's open.

3. save: save the note to the db.

2023-12-12 03:56 UTC, qingshuizheng commented on ekg.el
> +  (when (y-or-n-p "Are you sure you want to abort all the edits?")
This mimics how org-capture buffer works.

1. `ekg-{capture,edit}-abort` is triggered by C-c C-K, usually the user abort the note **on purpose**.

3. `ekg-kill-buffer-query-function` is triggered by `kill-buffer`, when buffer is modified. Since buffer kill is sometimes called by accident, a query here just serves as the last resort to save the unsaved data.

2023-12-12 04:18 UTC, qingshuizheng commented on ekg.el
> +                 (const :tag "Abort unsaved changes" abort-unsaved)
Reword the docstring a little bit:

```emacs lisp
(defcustom ekg-save-action-on-buffer-kill 'query
  "Action to take for unsaved ekg editable buffer on buffer kill.
If value is \\='abort-unsaved, discard the unsaved changes, the
already saved part will be kept. If value is \\='abort-all, for
`ekg-capture-mode', the whole capture will be aborted; for
`ekg-edit-mode', all edits (saved or not) will be discarded, the
note will be restored to its original state at open. If value is
\\='save, save the note to db. If value is \\='query, ask the
user which action to take."
  :type '(choice (const :tag "Ask before killing" query)
                 (const :tag "Abort unsaved changes (the already saved part will be kept)" abort-unsaved)
                 (const :tag "Abort capture in ekg-capture-mode or abort all edits in ekg-edit-mode" abort-all)
                 (const :tag "Save note" save))
  :group 'ekg)
```

Or, implement only 3 options for less confusion: `abort`, `save`, `query`:

```emacs lisp
(defcustom ekg-save-action-on-buffer-kill 'query
  "Action to take for unsaved ekg editable buffer on buffer kill.
If value is \\='abort, for `ekg-capture-mode', the whole capture
will be aborted; for `ekg-edit-mode', all edits (saved or not)
will be discarded, the note will be restored to its original
state at open. If value is \\='save, save the note to db. If
value is \\='query, ask the user which action to take."
  :type '(choice (const :tag "Ask before killing" query)
                 (const :tag "Abort capture in ekg-capture-mode or abort edits in ekg-edit-mode" abort)
                 (const :tag "Save note" save))
  :group 'ekg)

```

2023-12-12 10:30 UTC, qingshuizheng commented
Pushed two new commits: 
1. fix a wrongly placed "t" in `ekg-buffer-kill-query-function`, which leads to buffer not killed after save.
2. improve docstring for user option `ekg-save-action-on-buffer-kill`.

2023-12-14 05:25 UTC, ahyatt commented
Thank you for all the changes so far.  We're close!  Maybe all the way there, but I want to continue to think about making things even clearer.  I'm not sure, though, so please be patient as I continue to think through this.

2023-12-14 06:42 UTC, qingshuizheng commented
Ahh no worry at all.

I planned to place this on `discussion` section. But since I have these changes in my personal branch, I think I could make a PR here, so that you could play with it, then decide whether you like it or not.

2023-12-26 05:46 UTC, merged

2023-12-26 05:47 UTC, ahyatt commented
Thanks for bearing with me - this looks good.  I want to make a few changes and test this out, but this will be nice to have for the next release.  Thanks again for your effort in putting this together.

2023-12-26 10:34 UTC, qingshuizheng commented
Thanks for the review and merge. Feel free to make any changes to fit the repo.