Several trivial changes
ahyatt/ekg pull request #133
Opened 2024-01-17 01:13 UTC by qingshuizheng

Hello Andrew,

In this PR, several changes are made:

1. Internalize func name:
ekg-kill-buffer-query-function -> ekg--kill-buffer-query-function ;
ekg-header-line-format  -> ekg--header-line-format

2. Remove redundant code in the definition of ekg-capture-mode, which is already included in `(ekg--set-local-variables)`

3. `ekg-clean-dup-tags` should act on every tag, instead of only the incomplete `(ekg-tags)`.

4. Insert newest note on top of ekg-notes-mode by default for easy browsing. The cursor will jump to the the top of buffer on every refresh. Put the newest note on top will make it easy to find.

5. Also insert newly captured note to the ekg-show-notes-latest-{modified,captured} buffer.

6. Refresh only the edited note, instead of refreshing all the notes for better performance, and avoid cursor jumping around.

7. Simplify code: ekg-display-note-titled, ekg-notes-{next,prev}

Let me know what you think and feel free to take or reject any of them.

Zheng

2024-01-17 02:26 UTC, ahyatt commented
Thank you for this change!  FYI, I'm going to be flying and on vacation in the next 2 weeks, but I'll have time to look this over.  But it might not be for a few days.

2024-01-17 02:45 UTC, qingshuizheng commented
Wow, enjoy the vacations! 🍾  Just leave everything here as is until you come back.

2024-01-21 16:28 UTC, ahyatt requested changes

2024-01-21 16:28 UTC, ahyatt commented on ekg.el
> +                       ?\: (zero-or-more whitespace)
Can you explain this change?  I think there should always be at leaset one space after the colon.

2024-01-21 16:28 UTC, ahyatt commented on ekg.el
> +    (mapc (lambda (note) (ewoc-enter-first ewoc note)) (funcall notes-func))
Can you explain why this is better?  Maybe add a comment about it, as well.

2024-01-22 00:31 UTC, qingshuizheng commented on ekg.el
> +                       ?\: (zero-or-more whitespace)
Since a colon (":") would split the line into label and its values correctly, I think zero whitespace could be allowed.

Very often I would miss the whitespace after colon. Even tho I notice there is a missing whitespace thereafter, moving cursor back to the title to fix it is kinda bummer.

```
---metadata overlay---
Tags: date/2024-01-22
Title:Another good day!
---metadata overlay---

Pellentesque dapibus suscipit ligula. Donec posuere augue in quam.
Etiam vel tortor sodales tellus ultricies commodo. Suspendisse
potenti. Aenean in sem ac leo mollis blandit. Donec neque quam,
dignissim in, mollis nec, sagittis eu, wisi. Phasellus lacus. Etiam
laoreet quam sed arcu. Phasellus at dui in ligula mollis ultricies.
Integer placerat tristique nisl. Praesent augue. Fusce commodo.
Vestibulum convallis, lorem a tempus semper, dui dui euismod elit,
vitae placerat urna tortor vitae lacus.

I AM HERE! 
OOOPS! Whitespace after colon in title field is missing!
Now I need to move to the line-start to fix the whitespace after ":".
```

I cannot think of a reason not to allow zero-or-more whitespace except for cosmetic reason.

2024-01-22 00:59 UTC, qingshuizheng commented on ekg.el
> +    (mapc (lambda (note) (ewoc-enter-first ewoc note)) (funcall notes-func))
By default `M-x ekg-show-notes-in-drafts RET` would sort the newest note at BOTTOM, but when you press "g" (key for `ekg-notes-refresh`), the newest note will be reverted to the TOP of the buffer. It occurs to `ewoc-refresh` as well. This behavior could be really weird.

`ewoc-enter-first` could be the solution, placing the newest note on top, so there won't be a weird reversion on first refresh after `M-x ekg-show-notes* RET` commands. 

Another solution is to sort the notes with `ekg-sort-by-creation-time` in `ekg-setup-notes-buffer` like I have done in the same commit to `ekg-show-notes-in-drafts`.

2024-01-22 03:16 UTC, qingshuizheng commented on ekg.el
> +    (mapc (lambda (note) (ewoc-enter-first ewoc note)) (funcall notes-func))
Emm..realize the explanation above does not conform to change's real effects. Let me experiment with it a little bit and come back later.

2024-01-23 21:05 UTC, qingshuizheng commented on ekg.el
> +    (mapc (lambda (note) (ewoc-enter-first ewoc note)) (funcall notes-func))
Turns out that's a BRAINDEAD 'query replace all' mistake 😢 . I've pushed a fixup! commit to reverse the hunk! Thanks for the good caught!

2024-01-23 23:35 UTC, ahyatt commented
Thanks - I think this looks good! I'm hoping to merge this in and release 0.5 after a bit more of testing.   I take it your last commit has fixed whatever you needed to have fixed, and it's ready to merge in?

2024-01-23 23:43 UTC, qingshuizheng commented
> I'm hoping to merge this in and release 0.5 after a bit more of testing. 
Sure. And welcome to rebase them or do whatever change you think it should. 

> I take it your last commit has fixed whatever you needed to have fixed, and it's ready to merge in?
Correct. I won't push any more commit from here. Only exception is that there are issues needs to be addressed. But I'll let you know then.

Enjoy the vacation!

2024-01-24 00:18 UTC, merged

2024-01-24 00:20 UTC, ahyatt commented
Thank you for the fixes, and your continued improvements to this project!