Ekg denote
ahyatt/ekg pull request #143
Opened 2024-03-10 15:29 UTC by jayrajput

Export of Ekg to denote notes. Documentations updates are pending. Lot of stuff is not perfect, so feel free to comment and I will make the changes as per the guidance.

2024-03-10 19:57 UTC, ahyatt reviewed
Thank you very much for contributing this!  Will you be available if others use this and need bugfixes or have questions?

Also, can you add some information in the manual `doc/ekg.org` about this, explaining how it is used and anything the user has to understand when syncing to denote?

2024-03-10 19:57 UTC, ahyatt commented on ekg-denote.el
> +;; Copyright (c) 2024  Andrew Hyatt <ahyatt@gmail.com>
Please substitute your name and email address (unless you'd prefer to remain anonymous and assign me copyright).

2024-03-10 19:57 UTC, ahyatt commented on ekg-denote.el
> +  "Maximum length of the title to trim during export."
"to trim to" (I think, in other words, if it's longer than this, it will get trimmed)

2024-03-10 19:57 UTC, ahyatt commented on ekg-denote.el
> +  "Maximum length of the combined kws used for trimming kws when converting tags to kws during export."
Is "kws" keywords?  I'm not familiar with this terminology, is it a denote thing?

2024-03-10 19:57 UTC, ahyatt commented on ekg-denote.el
> +	 (ekg-title (or (car (plist-get (ekg-note-properties note) :titled/title)) ""))
Is it OK for the title to be empty like this in denote?

2024-03-10 19:57 UTC, ahyatt commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
The notion of merging during import/export is strange to me, can you explain in a comment or the file header what's going on here?

2024-03-11 02:49 UTC, jayrajput commented on ekg-denote.el
> +;; Copyright (c) 2024  Andrew Hyatt <ahyatt@gmail.com>
done.

2024-03-11 02:50 UTC, jayrajput commented on ekg-denote.el
> +	 (ekg-title (or (car (plist-get (ekg-note-properties note) :titled/title)) ""))
yes title being empty is OK in denote..

2024-03-11 02:54 UTC, jayrajput commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
Syncing between two systems is challenging. Ekg has a concept of backups, whereas denote does not have an inbuilt mechanism. Merging can be seen as a backup mechanism. Ideally denote notes should be git backed and this kind of merging shall not be needed. Just slapping the contents of Ekg to denote is scary and so the merging to take a backup. Not sure, if I am overdoing this, rather than human errors, I am worried about some code bug overwriting the data.

What do you say? Case of overthinking?

I have not yet written import, but the same will happen if the note is updated both in Ekg and Denote during import.

Thinks become interesting when an overwhelmed user re-runs export multiple times (and may have auto git checkin place) and no merging is in place.

2024-03-11 02:58 UTC, jayrajput commented on ekg-denote.el
> +  "Maximum length of the combined kws used for trimming kws when converting tags to kws during export."
updated to keywords.

2024-03-11 03:00 UTC, jayrajput commented
I will make myself available for support, but it will be good to get support. The code is straightforward and I am hoping it would not be that much trouble. I have a full time job and a kid, so there may be some lag during support. Although I use the code for personal notes, I am very much interested in finding and fixing. Updating the documentation.

2024-03-12 05:18 UTC, ahyatt requested changes

2024-03-15 15:35 UTC, jayrajput commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
I can create backup of denote and let ekg win. I was not aware about the `backup-buffer` command, that should do the job. I will drop the idea of manual merge though.

2024-03-15 15:36 UTC, jayrajput commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
Also I plan to make updates over the weekend for the suggested changes.

2024-03-16 11:46 UTC, jayrajput commented on ekg-denote.el
> +  "Maximum length of the title to trim during export."
yes. Updated.

2024-03-16 13:12 UTC, jayrajput commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
Trying this code, but it does not work

```
(let ((make-backup-files t)
	  (backup-by-copying t)
	  (backup-inhibited nil))
      (with-current-buffer (create-file-buffer "/tmp/test")
	(backup-buffer)))
```

2024-03-16 13:17 UTC, jayrajput commented on ekg-denote.el
> +	     (message "ekg-denote: %s" (ekg-denote--note-print note))
I want to indicate the note which is missing the creation-time. Shall I add to that to the `error` call. That can be too big.

2024-03-16 13:18 UTC, jayrajput commented on ekg-denote.el
> +	     (message "ekg-denote: %s" (ekg-denote--note-print note))
Updated

2024-03-16 13:18 UTC, jayrajput commented on ekg-denote.el
> +	     (error (format "ekg-denote: note missing creation time.")))))
updated..

2024-03-16 13:19 UTC, jayrajput commented on ekg-denote.el
> +  (let ((notes (mapcar #'ekg-note-creation-time notes)))
done..

2024-03-16 13:47 UTC, jayrajput commented on ekg-denote-test.el
> +(ekg-deftest ekg-denote-test-last-import-export ()
I stole this for your test cases. I did ended up leaving a bug in the `set-last-export`. So, `ert` are indeed needed.

2024-03-16 13:50 UTC, jayrajput commented on ekg-denote.el
> +    (cl-loop for note in notes do
I was little happy looking at this code. I know it took a tons of time. I have reasons, job-changes, os-changes, setup-changes, but let us not go there. You always it should be easy enough to write out `ekg` db to any format and it indeed is. There will be bugs here and there. But incremental progress :-).

2024-03-16 14:56 UTC, ahyatt commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
The issue with your code is that you are setting values via `let`, but these values are buffer-local.  I confirmed the following works as a proof-of-concept:

```emacs-lisp
(defun ash/test-backup-file (file)
  "Backup (via emacs) FILE."
  (interactive "fFile to backup: ")
  (with-current-buffer (find-file-noselect file)
    (let ((make-backup-files t)
          (backup-by-copying t)
	  (backup-inhibited nil))
	  (backup-buffer))))
```

Keep in mind that no backup will be made if the backup is already there, which you can change by also setting `buffer-backed-up` to `nil`.

2024-03-16 16:42 UTC, jayrajput commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
For some reason, it is not working for me.

```
(with-current-buffer (create-file-buffer "~/org/denote/20240304T073034__test.org")
  (sleep-for 1)
  (let ((make-backup-files t)
	(backup-by-copying t)
	(backup-inhibited nil)
	(buffer-backed-up nil))
    (backup-buffer)))
```

Although if I open the buffer and `eval` the code from `let` onwards, it works.

2024-03-16 16:47 UTC, jayrajput commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
`create-file-buffer` seems to be fine.

```
(create-file-buffer "~/org/denote/20240304T073034__test.org")
#<buffer 20240304T073034__test.org<10>>
```

2024-03-16 17:52 UTC, ahyatt commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
I don't think `create-file-buffer` is what you want - it doesn't actually load the file as far I can tell.  Instead, use `find-file-noselect`.  I reproduced the problem you had, and when I switched to `find-file-noselect`, it fixed the issue.

2024-03-17 03:58 UTC, ahyatt commented on ekg-denote.el
> +    (cl-loop for note in notes do
Yeah, this is great, you should feel super good about doing this.  It's "easy", but also not that easy to get it all right, so, well done!

2024-03-17 15:40 UTC, jayrajput commented on ekg-denote.el
> +(defvar ekg-denote-section-header (make-string 7 ?>) "Section header used during merging.")
Thanks. I have updated the code and verified that it works.

2024-03-17 15:42 UTC, jayrajput commented
I am done with the changes. I have resolved the minor conversations, except the one where we talked about merging and the backup. The code is updated, although I let it for you to resolve the conversation. Let me know if there are any further comments.

2024-03-17 17:36 UTC, ahyatt commented
Thanks, it looks good except for one detail: this pull request should be against the `develop` branch instead of the `main` branch.  That way I can do a few things before releasing it.

2024-03-18 01:09 UTC, closed without merging

2024-03-18 01:11 UTC, jayrajput commented
I have closed this PR and created a new one for ekg-denote