Notes browse for Local Files
ahyatt/ekg pull request #73
Opened 2023-06-07 06:33 UTC by jayrajput

Updated the ekg-notes-browse to be able to browse to local file in addition to web addresses. I also updated the documentation org to indicate the change.

2023-06-10 20:38 UTC, ahyatt requested changes
Thanks for this change!

2023-06-10 20:38 UTC, ahyatt commented on ekg.el
> +  (let* ((struct (url-generic-parse-url url))
I think we haven't used these functions before, so you can you `(require 'url-parse)`?

2023-06-10 20:38 UTC, ahyatt commented on ekg.el
> +(defcustom ekg-notes-browse-func 'ekg--browse-url
Should we make it clear that this is a URL browsing function, because maybe there will be others (the way `ekg-notes-browse` is written indicates that this is possible).

2023-06-10 20:38 UTC, ahyatt commented on ekg.el
> +        (find-file file)))))
Do we want to test if the file exists, and do something if it doesn't?  In the `bookmarks` package, they prompt to relocate, but here perhaps an error would be better than opening a new file.  On the other hand, maybe opening a new file is fine?  I'm not sure yet, let me know what you think.

2023-06-10 20:38 UTC, ahyatt commented on doc/ekg.org
> +By default, Ekg uses its own simple note browsing function which opens web addresses in browser using =browse-url= and everything else in Emacs using =find-file=.
I lowercase ekg in the manual.

2023-06-10 20:38 UTC, ahyatt commented on doc/ekg.org
> +Users who want to benefit from the more advanced URL/link browsing that is common in interactions with Org mode, can set the user option =ekg-notes-browse-func= to =org-link-open-from-string=.
I think the resources (ids) would be org-mode links, not URLs.  That's fine, but you might want to call this out; if users want to change the value, they would have to also change their resources.

2023-06-11 01:54 UTC, jayrajput commented on ekg.el
> +        (find-file file)))))
There may be a use case where the default behaviour of find-file may be desired (although no concrete use case). The `find-file` function does provide an indication on new vs existing file. I will prefer to leave as it is for now. `The markdown-follow-wiki-link` use the `find-file` so there are some precedence of using `find-file` as well.

We can choose to make the behaviour configurable, and let the end user decide the behaviour, but that capability is already available.

I am not making any changes for this suggestion for now.

2023-06-11 01:56 UTC, jayrajput commented on doc/ekg.org
> +By default, Ekg uses its own simple note browsing function which opens web addresses in browser using =browse-url= and everything else in Emacs using =find-file=.
done.

2023-06-11 02:06 UTC, jayrajput commented on doc/ekg.org
> +Users who want to benefit from the more advanced URL/link browsing that is common in interactions with Org mode, can set the user option =ekg-notes-browse-func= to =org-link-open-from-string=.
Made some updates. My basic usage of =org-link-open-from-string= works fine, but I agree that may not be true for all the cases and the updates may be needed.

2023-06-11 02:11 UTC, jayrajput commented on ekg.el
> +(defcustom ekg-notes-browse-func 'ekg--browse-url
rename the `ekg-browse-url` to `ekg--browse-url-or-find-file`. The `ekg-notes-browse-func` and `ekg-notes-browse` both can evolve to handle other ways to browse.

2023-06-11 02:11 UTC, jayrajput commented on ekg.el
> +  (let* ((struct (url-generic-parse-url url))
Thanks. I have updated.

2023-06-11 08:30 UTC, jayrajput commented on ekg-logseq.el
> +  (message "ekg-logseq-sync: Starting in the background")
I was looking at this for denote and got tempted to fix the typo. Let me know what is the preference for future. Push them to a separate PR or OK to fix them on the spot.

2023-06-12 06:45 UTC, jayrajput commented on ekg.el
> +(defcustom ekg-notes-browse-func 'ekg--browse-url
I am setting the ekg-notes-browse-func to org-link-open-from-string which can open pdf files in system rather than in emacs.

2023-06-12 20:38 UTC, ahyatt commented
Thank you, this looks good right now!  I'm going to hold off on merging it in until I release ekg 0.3.1, though, since that has those necessary upgrade fixes, so is urgent enough that I don't want significant new functionality complicating the release.

2023-06-16 01:27 UTC, merged