Use key/val parameter in `ekg-note-create` & `ekg-capture`
ahyatt/ekg pull request #77
Opened 2023-06-12 04:24 UTC by qingshuizheng

Discussion: https://github.com/ahyatt/ekg/discussions/74
1. Usage of key/val form in parameter improves readability/flexibility.
2. Any essential key that is nil, would be set to default vaule
   1). text: nil --> ""
   2). tags: nil --> (ekg-date-tag), even when ekg-template-tag set nil
   3). mode: nil --> ekg-capture-default-mode
   4). id: --> (ekg--generate-id)

2023-06-14 04:46 UTC, ahyatt requested changes
Thank you for this change, I like how it improves things

2023-06-14 04:46 UTC, ahyatt commented on ekg.el
> +         (tags (or tags (ekg-date-tag)))) ; in case `ekg-capture-auto-tag-funcs` is nil'
I think it's better to leave tags as nil.  It's OK to have no tags if `ekg-capture-auto-tag-funcs` is nil, the note can still be found in the latest notes, or by title, or by searching.

2023-06-14 04:46 UTC, ahyatt commented on ekg-org-roam.el
> +                                                   (cons
Are these tabs here and below?  If so, can you please replace them with spaces?

2023-06-14 04:46 UTC, ahyatt commented on ekg.el
> +If id is given, force the triple subject to be that value."
ID should still be capitalized, like all function arguments in docstrings.

2023-06-14 11:28 UTC, qingshuizheng commented on ekg.el
> +         (tags (or tags (ekg-date-tag)))) ; in case `ekg-capture-auto-tag-funcs` is nil'
I thought :tags cannot be nil. TIL.
I will remove it from the `let*-form`.

2023-06-14 11:30 UTC, qingshuizheng commented on ekg-org-roam.el
> +                                                   (cons
They are spaces:

```
             position: 5807 of 6704 (87%), column: 50
            character: SPC (displayed as SPC) (codepoint 32, #o40, #x20)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x20
               script: latin
               syntax:   	which means: whitespace
             category: .:Base, a:ASCII, l:Latin
             to input: type "C-x 8 RET 20" or "C-x 8 RET SPACE"
          buffer code: #x20
            file code: #x20 (encoded by coding system prefer-utf-8-unix)
              display: by display table entry [?·] (see below)

The display table entry is displayed by these fonts (glyph codes):
·: mac-ct:-*-SauceCodePro Nerd Font-light-normal-normal-*-19-*-*-*-m-0-iso10646-1 (#x79)

Character code properties: customize what to show
  name: SPACE
  general-category: Zs (Separator, Space)
  decomposition: (32) (' ')

There are text properties here:
  face                 (whitespace-line whitespace-space)
  fontified            t

```

2023-06-14 11:37 UTC, qingshuizheng commented on ekg.el
> +If id is given, force the triple subject to be that value."
Changed. 

The reason for the change is, I feel "subject" is quite a concept in "triples", not in "ekg". 
Same change also occurs in `ekg-note-create`:
```elisp
(cl-defun ekg-note-create (&key text mode tags properties id)
  "Create a new `ekg-note' with TEXT, MODE, TAGS, PROPERTIES and ID."
...
...
...
```

2023-06-14 11:41 UTC, qingshuizheng commented
Glad you like the changes. :-D
Just force-pushed the requested changes.

2023-06-16 01:44 UTC, merged

2023-06-16 02:07 UTC, qingshuizheng commented
Cool, thanks!